- hosts: localhost
  vars:
    repos: "{{ lookup('env', 'HOME') }}/repos"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - include: /tasks/node.yml
    - include: /tasks/npm.yml
    - include: /tasks/git-setup.yml
    - include: /tasks/ts.yml 
    - include: /tasks/slack.yml
    - include: /tasks/chrome.yml
    - include: /tasks/core.yml
    - include: /tasks/docker.yml
    - include: /tasks/work-projects.yml
