- name: Install npm
  become: true
  apt:
    name: ["nodejs"]
  tags:
    - install

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags:
  - install

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
  - install

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - npm-path
